### ISSUE TITLE
The module does not seem to work on `localhost`

### ISSUE THREAD

**Issue by stefanobartoletti** [harlan-zw/nuxt-og-image#13]
### Describe the bug

When trying to access 

`https://localhost:3000/__og_image__`

from my browser, I only get a black page. Also, the image at 

`https://localhost:3000/__og_image__/og.png`

Is not existent.

### System Info

```Shell
System:
    OS: Linux 6.1 openSUSE Tumbleweed 20230212
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 4.29 GB / 15.04 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 9.4.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.158
    Chromium: 110.0.5481.77
    Firefox: 109.0.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nemure231** [comment]
I think have same problem, even can't generate og image in production build, hosted in Netlify, its just generate blank page. I do all step anyway. I just use `defineOgImageScreenshot()` function.

![test](https://user-images.githubusercontent.com/49015080/219479629-baf2f44a-cb77-4277-be79-f90dbb4593fd.jpg)

**Comment by harlan-zw** [comment]
Hey! Thanks fo rthe issue.

Could you confirm you're using the latest version and that you are SSR.

Otherwise please provide a `nuxi info` and I'll do my best to investigate.

Any type of reproduction would be very help.

**Comment by Nemure231** [comment]
Hi, first thing. i Figured out if i install it, as dependencies, like this:

```json
 "dependencies": {
    "nuxt-og-image": "^1.4.21"
  }
```
it's can generate og image in local anyway.
![Screenshot 2023-02-26 195912](https://user-images.githubusercontent.com/49015080/221413131-1c5fb1e8-f6fa-4fbe-baa7-07b1cf733cbb.jpg)


But still, can't generate og in production build. I am wondering if there any spesification about hosting? Maybe this is because i am using netlify free plan?

here is my reproduction: https://github.com/Nemure231/og_img_reproduction

```
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.9.3`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`
- Runtime Modules:  `nuxt-og-image@1.4.21`
- Build Modules:    `-`
```

**Comment by Nemure231** [comment]
After see the official site example that generate automatic og image with time, and its using vercel edge. Its just hosting problem maybe, however trying to investigate would be nice. :)

Anyway, i am already find alternative with prerender og in my problem with production build. This issue could be close, since i've tested by my self its works well in localhost now. Not sure its works on OP side, its his issue afterall.

**Comment by harlan-zw** [comment]
You _might_ have some success with 1.5.0 but it's a bit hard to debug. If you have provide any sort of reproduction I can look into it further.

**Comment by stefanobartoletti** [comment]
Thanks, I will check it, at the moment I'm working on a private repo because I am using some personal API keys to get content. I will see if I can manage to reproduce the issue on another minimal public configuration

**Comment by harlan-zw** [comment]
Going to close for now, please try v2 beta if you are still having issues
