### ISSUE TITLE
404 Island component not found since Nuxt 3.6.0

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-og-image#61]
### Describe the bug

Hey @harlan-zw, has anything changed since Nuxt 3.6.0? Can't figure out why things are not working after bumping nuxt to latest.
```
[nuxt-og-image 11:33:49 PM]  WARN  nuxt-og-image does not support the nitro target undefined with the runtime browser. Set runtimeBrowser: false to stop seeing this.
                                                                              11:33:47 PM
✔ Nitro built in 1449 ms                                                nitro 11:33:53 PM
ℹ Vite client warmed up in 2841ms                                             11:33:54 PM
✔ Vite server hmr 18 files in 1064.645ms                                      11:33:56 PM
[Vue warn]: Component <Anonymous> is missing template or render function.     11:33:56 PM
[11:33:57 PM] [nuxt] [request error] [unhandled] [404]  (404 Island component not found: undefined (/__nuxt_island/OgImageBasic:VvoKLzP9ba?
```
I basically took your "Minimal Playground Example" and bumped both `Nuxt` to v3.6.1 and `nuxt-og-image` to beta.58

### Reproduction

https://stackblitz.com/edit/nuxt-starter-p6wd8z?file=components%2FCustomBanner.island.vue

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules
- Runtime Modules:  nuxt-og-image@2.0.0-beta.58
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Thanks @tmlmt, looks like the Nuxt core is handling the island routes different as of 3.6.0, have pushed up a fix in beta.59

**Comment by tmlmt** [comment]
Thanks @harlan-zw! 

For the sake of clarity regarding the island component:
- Your [readme instructions](https://github.com/harlan-zw/nuxt-og-image#1-create-an-island-component) tells to place the component in `/components/islands/MyTemplate.vue`
- Your [Minimal Playground Example](https://stackblitz.com/edit/nuxt-starter-pxs3wk?file=pages/index.vue) has one as `/components/CustomBanner.island.vue`
- The [Nuxt docs](https://nuxt.com/docs/guide/directory-structure/components#standalone-server-components) seem to indicate that server components are registered with the suffix `.server` in e.g `/components/MyTemplate.server.vue`

Could you clarify what matters and what doesn't?

**Comment by harlan-zw** [comment]
As of [v2.0.0-beta.60](https://github.com/harlan-zw/nuxt-og-image/releases/tag/v2.0.0-beta.60), the recommendation will be to place the components in the `OgImage` folder by default.

Any components in these folders will be configured to be a Nuxt Island. You can extend the folders by using the `componentDirs` option if you prefer your own convention. Setting up components in this dir will also allow you to reference the component using a shorthand instead of the full path.

For example, a component at `./components/OgImage/Foo.vue` can be referenced as `defineOgImage({ component: 'foo' })` (instead of the full path)

Otherwise, any island components set up with the previous convention will still work.

Let me know if you have any feedback on that :)

**Comment by tmlmt** [comment]
It also worked before with a component placed directly in the `components` folder and the `server` suffix (e.g. `/components/CustomOg.server.vue`) and referencing the component without full path. But I think it makes sense to place the OgImage specific components in a subfolder for readability. So if it works your new way, thanks a lot @harlan-zw for clarifying things with the new convention 😊
